import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { Anek_Telugu } from "next/font/google";
import { notFound } from "next/navigation";
import "../../app/globals.css";
import { cn } from "../../lib/utils";
import { unstable_setRequestLocale } from "next-intl/server";


interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string }
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'de' }]
}
const AnekTelugu = Anek_Telugu({
  subsets: ["latin"],
  variable: "--font-caption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  let messages
  try {
    messages = (await import(`../../content/${locale}.json`)).default
  } catch (error) {
    console.error('Failed to load messages:', error);
    notFound()
  }
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale}>
      <body className={cn(GeistSans.variable,
        GeistMono.variable,
        AnekTelugu.variable,
        "font-sans h-full bg-background text-foreground"
      )}>
        <NextIntlClientProvider locale={locale} messages={messages}>

          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}


