import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale,
}: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
