import type { Metadata } from "next";
import { Anek_Telugu } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "../../app/globals.css";
import { cn } from "../../lib/utils";


interface RootLayoutProps {
  children: React.ReactNode;
  locale: never;
}

const AnekTelugu = Anek_Telugu({
  subsets: ["latin"],
  variable: "--font-caption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locale,
}: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className={cn(GeistSans.variable,
        GeistMono.variable,
        AnekTelugu.variable,
        "font-sans h-full bg-background text-foreground"
      )}>
        {children}
      </body>
    </html>
  );
}
